db.clientes.insertMany([
  {
    nombre: 'Chico',
    apellido: 'Lisciandro',
    direccion: '96 Graedel Way',
    codigo_postal: 18179,
    localidad: 'Sevilla',
    provincia: 'Spain',
    telefono: '235-164-6519',
  },
  {
    nombre: 'Danie',
    apellido: 'Ding',
    direccion: '34 Nobel Place',
    codigo_postal: 18382,
    localidad: 'Malaga',
    provincia: 'Spain',
    telefono: '808-956-1025',
  },
  {
    nombre: 'Abagail',
    apellido: 'Rain',
    direccion: '435 Hoepker Avenue',
    codigo_postal: 18241,
    localidad: 'Torrevieja',
    provincia: 'Spain',
    telefono: '163-782-7649',
  },
  {
    nombre: 'Robby',
    apellido: 'Killingsworth',
    direccion: '7 Marquette Crossing',
    codigo_postal: 18175,
    localidad: 'Malaga',
    provincia: 'Spain',
    telefono: '219-564-6736',
  },
  {
    nombre: 'Mirelle',
    apellido: 'Spong',
    direccion: '007 Merchant Avenue',
    codigo_postal: 18489,
    localidad: 'Cartagena',
    provincia: 'Spain',
    telefono: '730-230-2428',
  },
  {
    nombre: 'Ruby',
    apellido: 'Chilles',
    direccion: '64556 Dottie Circle',
    codigo_postal: 18533,
    localidad: 'Fuenlabrada',
    provincia: 'Spain',
    telefono: '675-200-5383',
  },
  {
    nombre: 'Dalila',
    apellido: 'Solon',
    direccion: '777 Spenser Point',
    codigo_postal: 18843,
    localidad: 'Toledo',
    provincia: 'Spain',
    telefono: '425-612-2333',
  },
  {
    nombre: 'Mildrid',
    apellido: 'Wimpey',
    direccion: '55865 Vahlen Park',
    codigo_postal: 18180,
    localidad: 'Vigo',
    provincia: 'Spain',
    telefono: '808-791-7533',
  },
  {
    nombre: 'Sammy',
    apellido: 'Haydney',
    direccion: '0601 Novick Place',
    codigo_postal: 18011,
    localidad: 'Madrid',
    provincia: 'Spain',
    telefono: '590-913-1627',
  },
  {
    nombre: 'Gilberto',
    apellido: 'Izard',
    direccion: '0535 Laurel Court',
    codigo_postal: 18573,
    localidad: 'Cartagena',
    provincia: 'Spain',
    telefono: '769-328-8194',
  },
]);

db.tiendas.insertMany([
  {
    direccion: [
      {
        calle: "La Font d'en Fargues",
        codigo_postal: 08032,
        localidad: 'Barcelona',
        provincia: 'Cataluña',
      },
    ],
    empleados: [
      {
        id: 1,
        nombre: 'Letisha',
        apellido: 'Clawe',
        NIF: '56467715P',
        telefono: '983-453-7202',
        rol: 'cocinero',
      },
      {
        id: 2,
        nombre: 'Chloette',
        apellido: 'Scheu',
        NIF: '79156744R',
        telefono: '615-567-2934',
        rol: 'repartidor',
      },
      {
        id: 3,
        nombre: 'De',
        apellido: 'Conrard',
        NIF: '28986215T',
        telefono: '276-109-1714',
        rol: 'repartidor',
      },
    ],
  },
  {
    direccion: [
      {
        calle: 'Raval de Montserrat',
        codigo_postal: 08221,
        localidad: 'Terrassa',
        provincia: 'Cataluña',
      },
    ],
    empleados: [
      {
        id: 4,
        nombre: 'Murdock',
        apellido: 'Christescu',
        NIF: '36730839R',
        telefono: '624-818-6719',
        rol: 'cocinero',
      },
      {
        id: 5,
        nombre: 'Kevan',
        apellido: 'Tinner',
        NIF: '68372103P',
        telefono: '672-836-7704',
        rol: 'repartidor',
      },
      {
        id: 6,
        nombre: 'Ransell',
        apellido: 'McIver',
        NIF: '50753754Q',
        telefono: '929-780-2071',
        rol: 'repartidor',
      },
    ],
  },
  {
    direccion: [
      {
        calle: 'Av. de Josep Tarradellas',
        codigo_postal: 08901,
        localidad: "L'Hospitalet del Llobregat",
        provincia: 'Cataluña',
      },
    ],
    empleados: [
      {
        id: 7,
        nombre: 'Myrtle',
        apellido: 'Ellcome',
        NIF: '71648711P',
        telefono: '390-420-8899',
        rol: 'cocinero',
      },
      {
        id: 8,
        nombre: 'Thomasine',
        apellido: 'Timbs',
        NIF: '53423655R',
        telefono: '371-442-6971',
        rol: 'repartidor',
      },
      {
        id: 9,
        nombre: 'Raymond',
        apellido: 'Krauze',
        NIF: '88424717T',
        telefono: '453-585-9880',
        rol: 'repartidor',
      },
    ],
  },
  {
    direccion: [
      {
        calle: 'Carrer de Luxemburg',
        codigo_postal: 08917,
        localidad: 'Badalona',
        provincia: 'Cataluña',
      },
    ],
    empleados: [
      {
        id: 10,
        nombre: 'Ellyn',
        apellido: 'Soame',
        NIF: '39554938R',
        telefono: '918-532-1502',
        rol: 'cocinero',
      },
      {
        id: 11,
        nombre: 'Jean',
        apellido: 'Thame',
        NIF: '71322498P',
        telefono: '780-603-3494',
        rol: 'repartidor',
      },
      {
        id: 12,
        nombre: 'Audy',
        apellido: 'Baser',
        NIF: '63959209E',
        telefono: '605-358-5046',
        rol: 'repartidor',
      },
    ],
  },
]);

db.productos.insertMany([
  {
    tipo: 'Hamburguesa',
    categoria: '',
    nombre: 'Ternera',
    descripcion: 'una hamburguesa con una solo carne tradicional',
    imagen: 'shorturl.at/flp78',
    precio: 10.99,
  },
  {
    tipo: 'Hamburguesa',
    categoria: '',
    nombre: 'Ternera Doble',
    descripcion: 'una hamburguesa de DOBLE carne tradicional',
    imagen: 'shorturl.at/BFHNV',
    precio: 12.99,
  },
  {
    tipo: 'Hamburguesa',
    categoria: '',
    nombre: 'Pollo',
    descripcion: 'una hamburguesa de pollo a la plancha',
    imagen: 'shorturl.at/dkuG4',
    precio: 9.99,
  },
  {
    tipo: 'Bebida',
    categoria: '',
    nombre: 'Coca-Cola',
    descripcion: 'lata de Coca-Cola',
    imagen: 'shorturl.at/dlEMU',
    precio: 2.99,
  },
  {
    tipo: 'Bebida',
    categoria: '',
    nombre: 'Smoothie',
    descripcion: 'Smoothie de chocolata y leche de avena',
    imagen: 'shorturl.at/ekNQ5',
    precio: 5.99,
  },
  {
    tipo: 'Bebida',
    categoria: '',
    nombre: 'Agua',
    descripcion: 'botella con agua Bezoya',
    imagen: 'shorturl.at/kSW46',
    precio: 2.99,
  },
  {
    tipo: 'Pizza',
    categoria: 'Carnivora',
    nombre: 'Pepperoni',
    descripcion: 'pizza tradicional con queso y pepperoni',
    imagen: 'shorturl.at/lJW25',
    precio: 8.99,
  },
  {
    tipo: 'Pizza',
    categoria: 'Carnivora',
    nombre: 'Jamon',
    descripcion: 'pizza tradicional con queso y jamon',
    imagen: 'shorturl.at/GLOZ5',
    precio: 8.99,
  },
  {
    tipo: 'Pizza',
    categoria: 'Vegetariana',
    nombre: 'Hongos y Queso',
    descripcion: 'pizza tradicional con hongos y queso vegetariano',
    imagen: 'shorturl.at/CRS57',
    precio: 9.99,
  },
  {
    tipo: 'Pizza',
    categoria: 'Vegetariana',
    nombre: 'Espinaca y Queso',
    descripcion: 'pizza tradicional con espinaca y queso vegetariano',
    imagen: 'shorturl.at/uwyQ3',
    precio: 9.99,
  },
  {
    tipo: 'Pizza',
    categoria: 'Tradicional Italiana',
    nombre: 'Margherita',
    descripcion: 'queso mozzarella, tomate, y oregano',
    imagen: 'shorturl.at/bKOWX',
    precio: 10.99,
  },
  {
    tipo: 'Pizza',
    categoria: 'Tradicional Italiana',
    nombre: 'Diavola',
    descripcion: 'queso mozzarella, tomate, salami y aceite de oliva',
    imagen: 'shorturl.at/dEOS3',
    precio: 10.99,
  },
]);

db.pedidos.insertMany([
  {
    cliente_id: 10,
    tienda_id: 4,
    fecha: '8/4/2022',
    hora: '2:15 PM',
    tipo: 'recogida',
    cant_bebidas: 1,
    cant_pizzas: 2,
    cant_hamburguesas: 0,
    precio: 5.54,
    empleado_id: 6,
  },
  {
    cliente_id: 10,
    tienda_id: 4,
    fecha: '8/3/2022',
    hora: '5:26 PM',
    tipo: 'recogida',
    cant_bebidas: 3,
    cant_pizzas: 2,
    cant_hamburguesas: 3,
    precio: 22.71,
    empleado_id: 5,
  },
  {
    cliente_id: 6,
    tienda_id: 3,
    fecha: '1/18/2022',
    hora: '5:16 PM',
    tipo: 'delivery',
    cant_bebidas: 3,
    cant_pizzas: 0,
    cant_hamburguesas: 1,
    precio: 41.46,
    empleado_id: 6,
  },
  {
    cliente_id: 4,
    tienda_id: 1,
    fecha: '2/18/2022',
    hora: '7:41 PM',
    tipo: 'recogida',
    cant_bebidas: 2,
    cant_pizzas: 2,
    cant_hamburguesas: 2,
    precio: 45.4,
    empleado_id: 11,
  },
  {
    cliente_id: 4,
    tienda_id: 4,
    fecha: '8/16/2022',
    hora: '7:56 PM',
    tipo: 'recogida',
    cant_bebidas: 2,
    cant_pizzas: 1,
    cant_hamburguesas: 1,
    precio: 9.77,
    empleado_id: 12,
  },
  {
    cliente_id: 10,
    tienda_id: 2,
    fecha: '9/13/2022',
    hora: '12:15 PM',
    tipo: 'delivery',
    cant_bebidas: 0,
    cant_pizzas: 2,
    cant_hamburguesas: 2,
    precio: 61.64,
    empleado_id: 4,
  },
  {
    cliente_id: 3,
    tienda_id: 2,
    fecha: '2/16/2022',
    hora: '3:28 PM',
    tipo: 'recogida',
    cant_bebidas: 1,
    cant_pizzas: 0,
    cant_hamburguesas: 1,
    precio: 44.4,
    empleado_id: 7,
  },
  {
    cliente_id: 4,
    tienda_id: 3,
    fecha: '10/17/2022',
    hora: '12:03 PM',
    tipo: 'recogida',
    cant_bebidas: 0,
    cant_pizzas: 1,
    cant_hamburguesas: 2,
    precio: 49.67,
    empleado_id: 12,
  },
  {
    cliente_id: 10,
    tienda_id: 3,
    fecha: '4/28/2022',
    hora: '12:19 PM',
    tipo: 'recogida',
    cant_bebidas: 2,
    cant_pizzas: 3,
    cant_hamburguesas: 1,
    precio: 50.93,
    empleado_id: 12,
  },
  {
    cliente_id: 7,
    tienda_id: 2,
    fecha: '1/13/2022',
    hora: '6:25 PM',
    tipo: 'recogida',
    cant_bebidas: 0,
    cant_pizzas: 0,
    cant_hamburguesas: 3,
    precio: 11.58,
    empleado_id: 1,
  },
  {
    cliente_id: 9,
    tienda_id: 4,
    fecha: '4/7/2022',
    hora: '4:34 PM',
    tipo: 'delivery',
    cant_bebidas: 0,
    cant_pizzas: 3,
    cant_hamburguesas: 3,
    precio: 21.76,
    empleado_id: 4,
  },
  {
    cliente_id: 4,
    tienda_id: 3,
    fecha: '6/9/2022',
    hora: '2:05 PM',
    tipo: 'delivery',
    cant_bebidas: 3,
    cant_pizzas: 2,
    cant_hamburguesas: 1,
    precio: 35.08,
    empleado_id: 5,
  },
  {
    cliente_id: 6,
    tienda_id: 3,
    fecha: '7/10/2022',
    hora: '8:37 PM',
    tipo: 'delivery',
    cant_bebidas: 1,
    cant_pizzas: 1,
    cant_hamburguesas: 2,
    precio: 41.94,
    empleado_id: 6,
  },
  {
    cliente_id: 4,
    tienda_id: 2,
    fecha: '4/15/2022',
    hora: '6:33 PM',
    tipo: 'recogida',
    cant_bebidas: 1,
    cant_pizzas: 1,
    cant_hamburguesas: 3,
    precio: 18.14,
    empleado_id: 5,
  },
  {
    cliente_id: 9,
    tienda_id: 4,
    fecha: '11/5/2022',
    hora: '6:47 PM',
    tipo: 'recogida',
    cant_bebidas: 0,
    cant_pizzas: 0,
    cant_hamburguesas: 0,
    precio: 46.62,
    empleado_id: 9,
  },
  {
    cliente_id: 3,
    tienda_id: 3,
    fecha: '3/16/2022',
    hora: '7:19 PM',
    tipo: 'recogida',
    cant_bebidas: 0,
    cant_pizzas: 2,
    cant_hamburguesas: 0,
    precio: 50.06,
    empleado_id: 12,
  },
  {
    cliente_id: 7,
    tienda_id: 4,
    fecha: '6/17/2022',
    hora: '8:23 PM',
    tipo: 'delivery',
    cant_bebidas: 0,
    cant_pizzas: 2,
    cant_hamburguesas: 3,
    precio: 18.58,
    empleado_id: 11,
  },
  {
    cliente_id: 8,
    tienda_id: 4,
    fecha: '11/14/2022',
    hora: '5:31 PM',
    tipo: 'delivery',
    cant_bebidas: 1,
    cant_pizzas: 2,
    cant_hamburguesas: 2,
    precio: 62.28,
    empleado_id: 2,
  },
  {
    cliente_id: 1,
    tienda_id: 1,
    fecha: '7/4/2022',
    hora: '12:19 PM',
    tipo: 'delivery',
    cant_bebidas: 3,
    cant_pizzas: 1,
    cant_hamburguesas: 1,
    precio: 19.46,
    empleado_id: 10,
  },
  {
    cliente_id: 4,
    tienda_id: 4,
    fecha: '9/17/2022',
    hora: '9:53 PM',
    tipo: 'delivery',
    cant_bebidas: 2,
    cant_pizzas: 2,
    cant_hamburguesas: 2,
    precio: 60.63,
    empleado_id: 5,
  },
]);
